version: '3.8'
services:
  marketplace:
    build:
      context: .
      dockerfile: marketplace/Dockerfile
    environment:
      RECOMMENDATIONS_HOST: recommendations
    # DOCKER_BUILDKIT=1 docker build . -f marketplace/Dockerfile \
    #                   -t marketplace --secret id=ca.key,src=ca.key
    image: marketplace
    networks:
      - microservices
    ports:
      - 5001:5000

  recommendations:
    # DOCKER_BUILDKIT=1 docker build . -f recommendations/Dockerfile \
    #                   -t recommendations --secret id=ca.key,src=ca.key
    build:
      context: .
      dockerfile: recommendations/Dockerfile
    image: recommendations
    networks:
      - microservices

networks:
  microservices:
